'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.4.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("MySQL ODBC 5.1 Driver")>  _
        Public Property MySQL_ODBC() As String
            Get
                Return CType(Me("MySQL_ODBC"),String)
            End Get
            Set
                Me("MySQL_ODBC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192.168.100.36")>  _
        Public Property MySQL_Server() As String
            Get
                Return CType(Me("MySQL_Server"),String)
            End Get
            Set
                Me("MySQL_Server") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("watergever")>  _
        Public Property MySQL_User() As String
            Get
                Return CType(Me("MySQL_User"),String)
            End Get
            Set
                Me("MySQL_User") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("water")>  _
        Public Property MySQL_Pass() As String
            Get
                Return CType(Me("MySQL_Pass"),String)
            End Get
            Set
                Me("MySQL_Pass") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Demo")>  _
        Public Property LoginName1() As String
            Get
                Return CType(Me("LoginName1"),String)
            End Get
            Set
                Me("LoginName1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-")>  _
        Public Property LoginName2() As String
            Get
                Return CType(Me("LoginName2"),String)
            End Get
            Set
                Me("LoginName2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-")>  _
        Public Property LoginName3() As String
            Get
                Return CType(Me("LoginName3"),String)
            End Get
            Set
                Me("LoginName3") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-")>  _
        Public Property LoginName4() As String
            Get
                Return CType(Me("LoginName4"),String)
            End Get
            Set
                Me("LoginName4") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-")>  _
        Public Property LoginName5() As String
            Get
                Return CType(Me("LoginName5"),String)
            End Get
            Set
                Me("LoginName5") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-")>  _
        Public Property LoginName6() As String
            Get
                Return CType(Me("LoginName6"),String)
            End Get
            Set
                Me("LoginName6") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-")>  _
        Public Property LoginName7() As String
            Get
                Return CType(Me("LoginName7"),String)
            End Get
            Set
                Me("LoginName7") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-")>  _
        Public Property LoginName8() As String
            Get
                Return CType(Me("LoginName8"),String)
            End Get
            Set
                Me("LoginName8") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Dsn=myodbc;uid=watergever;pwd=water")>  _
        Public ReadOnly Property MySQL() As String
            Get
                Return CType(Me("MySQL"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog1Vestiging1() As Boolean
            Get
                Return CType(Me("Inlog1Vestiging1"),Boolean)
            End Get
            Set
                Me("Inlog1Vestiging1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog2Vestiging1() As Boolean
            Get
                Return CType(Me("Inlog2Vestiging1"),Boolean)
            End Get
            Set
                Me("Inlog2Vestiging1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog3Vestiging1() As Boolean
            Get
                Return CType(Me("Inlog3Vestiging1"),Boolean)
            End Get
            Set
                Me("Inlog3Vestiging1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog4Vestiging1() As Boolean
            Get
                Return CType(Me("Inlog4Vestiging1"),Boolean)
            End Get
            Set
                Me("Inlog4Vestiging1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog5Vestiging1() As Boolean
            Get
                Return CType(Me("Inlog5Vestiging1"),Boolean)
            End Get
            Set
                Me("Inlog5Vestiging1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog6Vestiging1() As Boolean
            Get
                Return CType(Me("Inlog6Vestiging1"),Boolean)
            End Get
            Set
                Me("Inlog6Vestiging1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog7Vestiging1() As Boolean
            Get
                Return CType(Me("Inlog7Vestiging1"),Boolean)
            End Get
            Set
                Me("Inlog7Vestiging1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog8Vestiging1() As Boolean
            Get
                Return CType(Me("Inlog8Vestiging1"),Boolean)
            End Get
            Set
                Me("Inlog8Vestiging1") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BarCodeServer() As Boolean
            Get
                Return CType(Me("BarCodeServer"),Boolean)
            End Get
            Set
                Me("BarCodeServer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog1Vestiging2() As Boolean
            Get
                Return CType(Me("Inlog1Vestiging2"),Boolean)
            End Get
            Set
                Me("Inlog1Vestiging2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog2Vestiging2() As Boolean
            Get
                Return CType(Me("Inlog2Vestiging2"),Boolean)
            End Get
            Set
                Me("Inlog2Vestiging2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog3Vestiging2() As Boolean
            Get
                Return CType(Me("Inlog3Vestiging2"),Boolean)
            End Get
            Set
                Me("Inlog3Vestiging2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog4Vestiging2() As Boolean
            Get
                Return CType(Me("Inlog4Vestiging2"),Boolean)
            End Get
            Set
                Me("Inlog4Vestiging2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog5Vestiging2() As Boolean
            Get
                Return CType(Me("Inlog5Vestiging2"),Boolean)
            End Get
            Set
                Me("Inlog5Vestiging2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog6Vestiging2() As Boolean
            Get
                Return CType(Me("Inlog6Vestiging2"),Boolean)
            End Get
            Set
                Me("Inlog6Vestiging2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog7Vestiging2() As Boolean
            Get
                Return CType(Me("Inlog7Vestiging2"),Boolean)
            End Get
            Set
                Me("Inlog7Vestiging2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog8Vestiging2() As Boolean
            Get
                Return CType(Me("Inlog8Vestiging2"),Boolean)
            End Get
            Set
                Me("Inlog8Vestiging2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog1VestigingTot() As Boolean
            Get
                Return CType(Me("Inlog1VestigingTot"),Boolean)
            End Get
            Set
                Me("Inlog1VestigingTot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog2VestigingTot() As Boolean
            Get
                Return CType(Me("Inlog2VestigingTot"),Boolean)
            End Get
            Set
                Me("Inlog2VestigingTot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog3VestigingTot() As Boolean
            Get
                Return CType(Me("Inlog3VestigingTot"),Boolean)
            End Get
            Set
                Me("Inlog3VestigingTot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog4VestigingTot() As Boolean
            Get
                Return CType(Me("Inlog4VestigingTot"),Boolean)
            End Get
            Set
                Me("Inlog4VestigingTot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog5VestigingTot() As Boolean
            Get
                Return CType(Me("Inlog5VestigingTot"),Boolean)
            End Get
            Set
                Me("Inlog5VestigingTot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog6VestigingTot() As Boolean
            Get
                Return CType(Me("Inlog6VestigingTot"),Boolean)
            End Get
            Set
                Me("Inlog6VestigingTot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog7VestigingTot() As Boolean
            Get
                Return CType(Me("Inlog7VestigingTot"),Boolean)
            End Get
            Set
                Me("Inlog7VestigingTot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property Inlog8VestigingTot() As Boolean
            Get
                Return CType(Me("Inlog8VestigingTot"),Boolean)
            End Get
            Set
                Me("Inlog8VestigingTot") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("192.168.2.6")>  _
        Public Property labelprinterip() As String
            Get
                Return CType(Me("labelprinterip"),String)
            End Get
            Set
                Me("labelprinterip") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property printselect() As Boolean
            Get
                Return CType(Me("printselect"),Boolean)
            End Get
            Set
                Me("printselect") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property testserver() As Boolean
            Get
                Return CType(Me("testserver"),Boolean)
            End Get
            Set
                Me("testserver") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property dfdkleinprint() As Boolean
            Get
                Return CType(Me("dfdkleinprint"),Boolean)
            End Get
            Set
                Me("dfdkleinprint") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property Versie() As String
            Get
                Return CType(Me("Versie"),String)
            End Get
            Set
                Me("Versie") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Boek5.My.MySettings
            Get
                Return Global.Boek5.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
